load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Module",
    srcs = [
        "Module.swift",
    ],
    module_name = "Module",
    visibility = [
        "//visibility:public",
    ],
)
